---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.7
    run_list: apt


suites:
  - name: default
    run_list: gitrob
    attributes:
      postgresql:
        password:
          postgres: 'somepassword'
      gitrob:
        database:
          password: 'anotherpassword'
