name             'gitrob'
maintainer       'computerlyrik, Christian Fischer'
maintainer_email 'chef-cookbooks@computerlyrik.de'
license          'Apache 2.0'
description      'Installs/Configures gitrob'
long_description 'Installs/Configures gitrob'
version          '0.1.0'
